import numpy as np

from sasdata.data import SasData
from sasdata.data_backing import Group
from sasdata.dataset_types import one_dim, three_dim, two_dim
from sasdata.metadata import Instrument, Metadata, Source
from sasdata.postprocess import deduce_qz
from sasdata.quantities.quantity import Quantity
from sasdata.quantities.units import angstroms, per_angstrom, per_centimeter


def test_1d():
    q = [1, 2, 3, 4, 5]
    i = [5, 4, 3, 2, 1]

    q_quantity = Quantity(np.array(q), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Q': q_quantity,
        'I': i_quantity
    }

    data = SasData('TestData', data_contents, one_dim, Group('root', {}), True)

    assert all(data.abscissae.value == np.array(q))
    assert all(data.ordinate.value == np.array(i))


def test_2d():
    # This could be autogenerated but I am hard coding to reduce the logic in
    # the test.
    qx = [1, 1, 1, 2, 2, 2, 3, 3, 3]
    qy = [1, 2, 3, 1, 2, 3, 1, 2, 3]
    i = [1, 2, 3]

    qx_quantity = Quantity(np.array(qx), per_angstrom)
    qy_quantity = Quantity(np.array(qy), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'I': i_quantity
    }

    data = SasData('TestData', data_contents, two_dim, Group('root', {}), True)

    assert all(data.ordinate.value == np.array(i))
    assert (data.abscissae.value == np.array([[1, 1], [1, 2], [1, 3], [2, 1], [2, 2], [2, 3], [3, 1], [3, 2], [3, 3]])).all().all()

def test_3d():
    # test base 3D class
    qx = [1, 1, 1, 2, 2, 2, 3, 3, 3]
    qy = [1, 2, 3, 1, 2, 3, 1, 2, 3]
    qz = [0, 1, 0, 1, 0, 1, 0, 1, 0]
    i = [1, 2, 3]

    qx_quantity = Quantity(np.array(qx), per_angstrom)
    qy_quantity = Quantity(np.array(qy), per_angstrom)
    qz_quantity = Quantity(np.array(qz), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'Qz': qz_quantity,
        'I': i_quantity
    }

    data = SasData('TestData', data_contents, three_dim, Group('root', {}), True)

    assert (data._data_contents['Qx'].value == np.array(qx)).all()



    # test autogenerated qz from qx, qy, and wavelength
    wavelength = Quantity(1., angstroms)
    source = Source(radiation=None,
                    beam_shape=None,
                    beam_size=None,
                    wavelength=wavelength,
                    wavelength_max=None,
                    wavelength_min=None,
                    wavelength_spread=None)
    instrument = Instrument(collimations=[],
                            source=source,
                            detector=[])
    metadata=Metadata(title=None,
                      run=[],
                      definition=None,
                      process=[],
                      sample=None,
                      instrument=instrument,
                      raw=None)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'I': i_quantity
    }

    data = SasData('TestData', data_contents, two_dim, metadata, True)

    deduce_qz(data)

    assert (data._data_contents['Qz'].value != (0*data._data_contents['Qx'].value)).all()
