import numpy as np
import pytest

from sasdata.data import SasMeasurement
from sasdata.dataset_types import angle_dim, one_dim, three_dim, two_dim
from sasdata.postprocess import deduce_qz
from sasdata.quantities.constants import Pi
from sasdata.quantities.quantity import Quantity
from sasdata.quantities.units import none as unitless
from sasdata.quantities.units import per_angstrom, per_centimeter, radians


@pytest.mark.parametrize(
    "q, i",
    [(np.array([1, 2, 3, 4, 5]), np.array([5, 4, 3, 2, 1])), (np.array([2, 4, 1, 5, 3]), np.array([1, 2, 3, 4, 5]))],
)
def test_1d(q, i, basic_metadata):
    q_quantity = Quantity(q, per_angstrom)
    i_quantity = Quantity(i, per_centimeter)

    data_contents = {"Q": q_quantity, "I": i_quantity}

    data = SasMeasurement("TestData", data_contents, one_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 1
    assert all(data.abscissae.axes[0].value == q)
    assert all(data.ordinate == i_quantity)


# This could be autogenerated but I am hard coding to reduce the logic in the test.
@pytest.mark.parametrize(
    "qx, qy, i",
    [
        (
            np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]]),
            np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]),
            np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]),
        ),
        (np.array([1, 2]), np.array([1, 2, 3, 4, 5]), np.array([[1, 0, 1, 0, 1], [0, 1, 0, 1, 0]])),
    ],
)
def test_2d(qx, qy, i, basic_metadata):
    qx_quantity = Quantity(qx, per_angstrom)
    qy_quantity = Quantity(qy, per_angstrom)
    i_quantity = Quantity(i, per_centimeter)

    data_contents = {"Qx": qx_quantity, "Qy": qy_quantity, "I": i_quantity}

    data = SasMeasurement("TestData", data_contents, two_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 2
    assert (data.abscissae.axes[0].value == qx).all()
    assert (data.abscissae.axes[1].value == qy).all()
    assert (data.ordinate == i_quantity).all()


@pytest.mark.parametrize(
    "qx, qy, qz, i",
    [
        (
            np.array([[[1, 1], [1, 1]], [[2, 2], [2, 2]]]),
            np.array([[[1, 1], [2, 2]], [[1, 1], [2, 2]]]),
            np.array([[[1, 2], [1, 2]], [[1, 2], [1, 2]]]),
            np.array([[[1, 0], [1, 0]], [[0, 1], [0, 1]]]),
        ),
        (
            np.array([1, 2]),
            np.array([1, 2]),
            np.array([1, 2, 3, 4, 5]),
            np.array([[[1, 0, 1, 0, 1], [1, 0, 1, 0, 1]], [[0, 1, 0, 1, 0], [0, 1, 0, 1, 0]]]),
        ),
    ],
)
def test_3d(qx, qy, qz, i, basic_metadata):
    qx_quantity = Quantity(qx, per_angstrom)
    qy_quantity = Quantity(qy, per_angstrom)
    qz_quantity = Quantity(qz, per_angstrom)
    i_quantity = Quantity(i, per_centimeter)

    data_contents = {"Qx": qx_quantity, "Qy": qy_quantity, "Qz": qz_quantity, "I": i_quantity}

    data = SasMeasurement("TestData", data_contents, three_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 3
    assert (data.abscissae.axes[0].value == qx).all()
    assert (data.abscissae.axes[1].value == qy).all()
    assert (data.abscissae.axes[2].value == qz).all()
    assert (data.ordinate == i_quantity).all()


def test_deduce_qz(basic_metadata):
    root_two_pi = np.sqrt(2) * np.pi
    qx = np.array(
        [
            [root_two_pi, root_two_pi, root_two_pi],
            [root_two_pi, root_two_pi, root_two_pi],
            [root_two_pi, root_two_pi, root_two_pi],
        ]
    )
    qy = np.array(
        [
            [root_two_pi, root_two_pi, root_two_pi],
            [root_two_pi, root_two_pi, root_two_pi],
            [root_two_pi, root_two_pi, root_two_pi],
        ]
    )
    i = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

    qx_quantity = Quantity(qx, unitless) / basic_metadata.instrument.source.wavelength
    qy_quantity = Quantity(qy, unitless) / basic_metadata.instrument.source.wavelength
    i_quantity = Quantity(i, per_centimeter)

    data_contents = {"Qx": qx_quantity, "Qy": qy_quantity, "I": i_quantity}

    data = SasMeasurement("TestData", data_contents, two_dim, basic_metadata, True)
    qz = deduce_qz(data)

    assert qz.value.shape == data.abscissae.axes[0].value.shape
    assert (qz.value == 2 * np.pi).all()


def test_angle(basic_metadata):
    phi = np.array([0.4 * Pi, 0.8 * Pi, 1.2 * Pi, 1.6 * Pi, 2 * Pi])
    i = np.array([5, 4, 3, 2, 1])

    phi_quantity = Quantity(phi, radians)
    i_quantity = Quantity(i, per_centimeter)

    data_contents = {"Phi": phi_quantity, "I": i_quantity}

    data = SasMeasurement("TestData", data_contents, angle_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 1
    assert all(data.abscissae.axes[0].value == phi)
    assert all(data.ordinate == i_quantity)
