import numpy as np

from sasdata.data import SasMeasurement
from sasdata.dataset_types import angle_dim, one_dim, three_dim, two_dim
from sasdata.postprocess import deduce_qz
from sasdata.quantities.constants import Pi
from sasdata.quantities.quantity import Quantity
from sasdata.quantities.units import per_angstrom, per_centimeter, radians


def test_1d(basic_metadata):
    q = [1, 2, 3, 4, 5]
    i = [5, 4, 3, 2, 1]

    q_quantity = Quantity(np.array(q), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Q': q_quantity,
        'I': i_quantity
    }

    data = SasMeasurement('TestData', data_contents, one_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 1
    assert all(data.abscissae.axes[0].value == np.array(q))
    assert all(data.ordinate.value == np.array(i))


def test_2d(basic_metadata):
    # This could be autogenerated but I am hard coding to reduce the logic in
    # the test.
    qx = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
    qy = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
    i = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

    qx_quantity = Quantity(np.array(qx), per_angstrom)
    qy_quantity = Quantity(np.array(qy), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'I': i_quantity
    }

    data = SasMeasurement('TestData', data_contents, two_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 2
    assert (data.ordinate.value == np.array(i)).all()
    assert (data.abscissae.axes[0].value == np.array(qx)).all()
    assert (data.abscissae.axes[1].value == np.array(qy)).all()

def test_3d(basic_metadata):
    # test base 3D class
    qx = [[[1, 1], [2, 2]], [[1, 1], [2, 2]]]
    qy = [[[1, 1], [1, 1]], [[2, 2], [2, 2]]]
    qz = [[[1, 2], [1, 2]], [[1, 2], [1, 2]]]
    i = [[[1, 0], [1, 0]], [[0, 1], [0, 1]]]

    qx_quantity = Quantity(np.array(qx), per_angstrom)
    qy_quantity = Quantity(np.array(qy), per_angstrom)
    qz_quantity = Quantity(np.array(qz), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'Qz': qz_quantity,
        'I': i_quantity
    }

    data = SasMeasurement('TestData', data_contents, three_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 3
    assert (data.ordinate.value == np.array(i)).all()
    assert (data.abscissae.axes[0].value == np.array(qx)).all()
    assert (data.abscissae.axes[1].value == np.array(qy)).all()
    assert (data.abscissae.axes[2].value == np.array(qz)).all()


def test_deduce_qz(basic_metadata):
    qx = [[[1, 1], [2, 2]], [[1, 1], [2, 2]]]
    qy = [[[1, 1], [1, 1]], [[2, 2], [2, 2]]]
    i = [[[1, 0], [1, 0]], [[0, 1], [0, 1]]]

    qx_quantity = Quantity(np.array(qx), per_angstrom)
    qy_quantity = Quantity(np.array(qy), per_angstrom)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Qx': qx_quantity,
        'Qy': qy_quantity,
        'I': i_quantity
    }

    data = SasMeasurement('TestData', data_contents, two_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 2
    assert (data.ordinate.value == np.array(i)).all()
    assert (data.abscissae.axes[0].value == np.array(qx)).all()
    assert (data.abscissae.axes[1].value == np.array(qy)).all()

    deduce_qz(data)

    assert (data._data_contents['Qz'].value != (0*data._data_contents['Qx'].value)).all()

def test_angle(basic_metadata):
    phi = [0.4 * Pi, 0.8 * Pi, 1.2 * Pi, 1.6 * Pi, 2 * Pi]
    i = [5, 4, 3, 2, 1]

    phi_quantity = Quantity(np.array(phi), radians)
    i_quantity = Quantity(np.array(i), per_centimeter)

    data_contents = {
        'Phi': phi_quantity,
        'I': i_quantity
    }

    data = SasMeasurement('TestData', data_contents, angle_dim, basic_metadata, True)

    assert data.abscissae.dimensionality == 1
    assert all(data.abscissae.axes[0].value == np.array(phi))
    assert all(data.ordinate.value == np.array(i))
