# Generated by Django 5.1.6 on 2025-04-23 18:08

import data.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="opt in to make your data public"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="File name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default=None,
                        help_text="This is a file",
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="uploaded_files",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="opt in to make your data public"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("files", models.ManyToManyField(to="data.datafile")),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Title", max_length=500)),
                ("run", models.JSONField(default=data.models.empty_list)),
                ("definition", models.TextField(blank=True, null=True)),
                ("instrument", models.JSONField(blank=True, null=True)),
                ("process", models.JSONField(default=data.models.empty_list)),
                ("sample", models.JSONField(blank=True, null=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="data.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("variance", models.JSONField()),
                ("units", models.CharField(max_length=200)),
                ("hash", models.IntegerField()),
                ("label", models.CharField(max_length=50)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_contents",
                        to="data.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("zero", "0 [Add.Id.]"),
                            ("one", "1 [Mul.Id.]"),
                            ("constant", "Constant"),
                            ("variable", "Variable"),
                            ("neg", "Neg"),
                            ("reciprocal", "Inv"),
                            ("add", "Add"),
                            ("sub", "Sub"),
                            ("mul", "Mul"),
                            ("div", "Div"),
                            ("pow", "Pow"),
                            ("transpose", "Transpose"),
                            ("dot", "Dot"),
                            ("matmul", "MatMul"),
                            ("tensor_product", "TensorProduct"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=data.models.empty_dict)),
                ("label", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "child_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_operations",
                        to="data.operationtree",
                    ),
                ),
                (
                    "quantity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_tree",
                        to="data.quantity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("variance", models.JSONField()),
                ("units", models.CharField(max_length=200)),
                ("hash", models.IntegerField()),
                (
                    "derived_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="data.quantity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="opt in to make your data public"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublishedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("doi", models.URLField()),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_state",
                        to="data.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="data.session",
            ),
        ),
    ]
