# Generated by Django 5.1.5 on 2025-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_rename_data_datafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="opt in to make your data public"
            ),
        ),
    ]
