# Generated by Django 5.1.6 on 2025-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_alter_datafile_users_alter_dataset_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="definition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="instrument",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="process",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="raw_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="metadata",
            name="run",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="sample",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="title",
            field=models.CharField(default="Title", max_length=500),
        ),
        migrations.AddField(
            model_name="metadata",
            name="transmission_spectrum",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
