# Generated by Django 5.1.6 on 2025-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_alter_dataset_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationtree",
            name="operation",
            field=models.CharField(default="undefined", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationtree",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
    ]
