# Generated by Django 5.1.6 on 2025-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_operationtree_operation_operationtree_parameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metadata",
            name="raw_metadata",
        ),
        migrations.RemoveField(
            model_name="metadata",
            name="transmission_spectrum",
        ),
        migrations.AlterField(
            model_name="metadata",
            name="run",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
