# Generated by Django 5.1.6 on 2025-03-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_remove_metadata_raw_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationtree",
            name="parent_operation",
        ),
        migrations.AddField(
            model_name="operationtree",
            name="parent_operation1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_operations1",
                to="data.operationtree",
            ),
        ),
        migrations.AddField(
            model_name="operationtree",
            name="parent_operation2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_operations2",
                to="data.operationtree",
            ),
        ),
    ]
