# Generated by Django 5.1.6 on 2025-03-20 14:29

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0013_remove_operationtree_parent_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="process",
            field=models.JSONField(default=data.models.empty_list),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="run",
            field=models.JSONField(default=data.models.empty_list),
        ),
        migrations.AlterField(
            model_name="operationtree",
            name="operation",
            field=models.CharField(
                choices=[
                    ("zero", "0 [Add.Id.]"),
                    ("one", "1 [Mul.Id.]"),
                    ("constant", "Constant"),
                    ("variable", "Variable"),
                    ("neg", "Neg"),
                    ("reciprocal", "Inv"),
                    ("add", "Add"),
                    ("sub", "Sub"),
                    ("mul", "Mul"),
                    ("div", "Div"),
                    ("pow", "Pow"),
                    ("transpose", "Transpose"),
                    ("dot", "Dot"),
                    ("matmul", "MatMul"),
                    ("tensor_product", "TensorProduct"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operationtree",
            name="parameters",
            field=models.JSONField(default=data.models.empty_dict),
        ),
    ]
