# Generated by Django 5.1.6 on 2025-04-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0017_publishedstate_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationtree",
            name="quantity",
        ),
        migrations.AddField(
            model_name="quantity",
            name="operation_tree",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.operationtree",
            ),
        ),
    ]
