# Generated by Django 5.1.6 on 2025-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0018_remove_operationtree_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(default="placeholder", max_length=200),
            preserve_default=False,
        ),
    ]
