# Generated by Django 5.1.6 on 2025-04-10 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0022_remove_dataset_data_contents_quantity_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtree",
            name="parent_operation1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_operations1",
                to="data.operationtree",
            ),
        ),
        migrations.AlterField(
            model_name="operationtree",
            name="parent_operation2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_operations2",
                to="data.operationtree",
            ),
        ),
    ]
