# Generated by Django 5.1.6 on 2025-04-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0024_remove_dataset_metadata_metadata_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quantity",
            name="operation_tree",
        ),
        migrations.AddField(
            model_name="operationtree",
            name="quantity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_tree",
                to="data.quantity",
            ),
        ),
    ]
