# Generated by Django 5.1.6 on 2025-04-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0026_remove_session_dataset_dataset_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="published_state",
        ),
        migrations.AddField(
            model_name="publishedstate",
            name="session",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_state",
                to="data.session",
            ),
            preserve_default=False,
        ),
    ]
