# Generated by Django 5.1.6 on 2025-04-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_remove_session_published_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationtree",
            name="parent_operation1",
        ),
        migrations.RemoveField(
            model_name="operationtree",
            name="parent_operation2",
        ),
        migrations.AddField(
            model_name="operationtree",
            name="label",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="operationtree",
            name="next_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_operations",
                to="data.operationtree",
            ),
        ),
    ]
