# Generated by Django 5.1.6 on 2025-04-11 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0028_remove_operationtree_parent_operation1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationtree",
            old_name="next_operation",
            new_name="child_operation",
        ),
    ]
