# Generated by Django 5.1.6 on 2025-04-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0029_rename_next_operation_operationtree_child_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="derived_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="data.quantity",
            ),
        ),
    ]
