# Generated by Django 5.1.6 on 2025-04-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0030_quantity_derived_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quantity",
            name="derived_quantity",
        ),
        migrations.CreateModel(
            name="ReferenceQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("variance", models.JSONField()),
                ("units", models.CharField(max_length=200)),
                ("hash", models.IntegerField()),
                (
                    "derived_quantity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="data.quantity",
                    ),
                ),
            ],
        ),
    ]
