# Generated by Django 5.1.6 on 2025-04-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0031_remove_quantity_derived_quantity_referencequantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencequantity",
            name="derived_quantity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="data.quantity",
            ),
            preserve_default=False,
        ),
    ]
