warning_text = """

This file is autogenerated!

Do not edit by hand, instead edit the files that build it (%s)




DDDDDDDDDDDDD                              NNNNNNNN        NNNNNNNN                          tttt
D::::::::::::DDD                           N:::::::N       N::::::N                       ttt:::t
D:::::::::::::::DD                         N::::::::N      N::::::N                       t:::::t
DDD:::::DDDDD:::::D                        N:::::::::N     N::::::N                       t:::::t
  D:::::D    D:::::D    ooooooooooo        N::::::::::N    N::::::N   ooooooooooo   ttttttt:::::ttttttt
  D:::::D     D:::::D oo:::::::::::oo      N:::::::::::N   N::::::N oo:::::::::::oo t:::::::::::::::::t
  D:::::D     D:::::Do:::::::::::::::o     N:::::::N::::N  N::::::No:::::::::::::::ot:::::::::::::::::t
  D:::::D     D:::::Do:::::ooooo:::::o     N::::::N N::::N N::::::No:::::ooooo:::::otttttt:::::::tttttt
  D:::::D     D:::::Do::::o     o::::o     N::::::N  N::::N:::::::No::::o     o::::o      t:::::t
  D:::::D     D:::::Do::::o     o::::o     N::::::N   N:::::::::::No::::o     o::::o      t:::::t
  D:::::D     D:::::Do::::o     o::::o     N::::::N    N::::::::::No::::o     o::::o      t:::::t
  D:::::D    D:::::D o::::o     o::::o     N::::::N     N:::::::::No::::o     o::::o      t:::::t    tttttt
DDD:::::DDDDD:::::D  o:::::ooooo:::::o     N::::::N      N::::::::No:::::ooooo:::::o      t::::::tttt:::::t
D:::::::::::::::DD   o:::::::::::::::o     N::::::N       N:::::::No:::::::::::::::o      tt::::::::::::::t
D::::::::::::DDD      oo:::::::::::oo      N::::::N        N::::::N oo:::::::::::oo         tt:::::::::::tt
DDDDDDDDDDDDD           ooooooooooo        NNNNNNNN         NNNNNNN   ooooooooooo             ttttttttttt








                                  dddddddd
EEEEEEEEEEEEEEEEEEEEEE            d::::::d  iiii          tttt               BBBBBBBBBBBBBBBBB
E::::::::::::::::::::E            d::::::d i::::i      ttt:::t               B::::::::::::::::B
E::::::::::::::::::::E            d::::::d  iiii       t:::::t               B::::::BBBBBB:::::B
EE::::::EEEEEEEEE::::E            d:::::d              t:::::t               BB:::::B     B:::::B
  E:::::E       EEEEEE    ddddddddd:::::d iiiiiiittttttt:::::ttttttt           B::::B     B:::::Byyyyyyy           yyyyyyy
  E:::::E               dd::::::::::::::d i:::::it:::::::::::::::::t           B::::B     B:::::B y:::::y         y:::::y
  E::::::EEEEEEEEEE    d::::::::::::::::d  i::::it:::::::::::::::::t           B::::BBBBBB:::::B   y:::::y       y:::::y
  E:::::::::::::::E   d:::::::ddddd:::::d  i::::itttttt:::::::tttttt           B:::::::::::::BB     y:::::y     y:::::y
  E:::::::::::::::E   d::::::d    d:::::d  i::::i      t:::::t                 B::::BBBBBB:::::B     y:::::y   y:::::y
  E::::::EEEEEEEEEE   d:::::d     d:::::d  i::::i      t:::::t                 B::::B     B:::::B     y:::::y y:::::y
  E:::::E             d:::::d     d:::::d  i::::i      t:::::t                 B::::B     B:::::B      y:::::y:::::y
  E:::::E       EEEEEEd:::::d     d:::::d  i::::i      t:::::t    tttttt       B::::B     B:::::B       y:::::::::y
EE::::::EEEEEEEE:::::Ed::::::ddddd::::::ddi::::::i     t::::::tttt:::::t     BB:::::BBBBBB::::::B        y:::::::y
E::::::::::::::::::::E d:::::::::::::::::di::::::i     tt::::::::::::::t     B:::::::::::::::::B          y:::::y
E::::::::::::::::::::E  d:::::::::ddd::::di::::::i       tt:::::::::::tt     B::::::::::::::::B          y:::::y
EEEEEEEEEEEEEEEEEEEEEE   ddddddddd   dddddiiiiiiii         ttttttttttt       BBBBBBBBBBBBBBBBB          y:::::y
                                                                                                       y:::::y
                                                                                                      y:::::y
                                                                                                     y:::::y
                                                                                                    y:::::y
                                                                                                   yyyyyyy



                                                                      dddddddd
HHHHHHHHH     HHHHHHHHH                                               d::::::d
H:::::::H     H:::::::H                                               d::::::d
H:::::::H     H:::::::H                                               d::::::d
HH::::::H     H::::::HH                                               d:::::d
  H:::::H     H:::::H    aaaaaaaaaaaaa  nnnn  nnnnnnnn        ddddddddd:::::d
  H:::::H     H:::::H    a::::::::::::a n:::nn::::::::nn    dd::::::::::::::d
  H::::::HHHHH::::::H    aaaaaaaaa:::::an::::::::::::::nn  d::::::::::::::::d
  H:::::::::::::::::H             a::::ann:::::::::::::::nd:::::::ddddd:::::d
  H:::::::::::::::::H      aaaaaaa:::::a  n:::::nnnn:::::nd::::::d    d:::::d
  H::::::HHHHH::::::H    aa::::::::::::a  n::::n    n::::nd:::::d     d:::::d
  H:::::H     H:::::H   a::::aaaa::::::a  n::::n    n::::nd:::::d     d:::::d
  H:::::H     H:::::H  a::::a    a:::::a  n::::n    n::::nd:::::d     d:::::d
HH::::::H     H::::::HHa::::a    a:::::a  n::::n    n::::nd::::::ddddd::::::dd
H:::::::H     H:::::::Ha:::::aaaa::::::a  n::::n    n::::n d:::::::::::::::::d
H:::::::H     H:::::::H a::::::::::aa:::a n::::n    n::::n  d:::::::::ddd::::d
HHHHHHHHH     HHHHHHHHH  aaaaaaaaaa  aaaa nnnnnn    nnnnnn   ddddddddd   ddddd



"""
