"""
Builds a data file containing details of units
"""

import numpy as np
from collections import defaultdict

bigger_magnitudes = [
    ("E", None, "exa", 1e18),
    ("P", None, "peta", 1e15),
    ("T", None, "tera", 1e12),
    ("G", None, "giga", 1e9),
    ("M", None, "mega", 1e6),
    ("k", None, "kilo", 1e3) ]

smaller_magnitudes = [
    ("m", None, "milli", 1e-3),
    ("u", "µ", "micro", 1e-6),
    ("n", None, "nano", 1e-9),
    ("p", None, "pico", 1e-12),
    ("f", None, "femto", 1e-15),
    ("a", None, "atto", 1e-18)]

all_magnitudes = bigger_magnitudes + smaller_magnitudes

# Length, time, mass, current, temperature
base_si_units = [
    ("m", None, "meter", "meters", 1, 1, 0, 0, 0, 0, all_magnitudes),
    ("s", None, "second", "seconds", 1, 0, 1, 0, 0, 0, smaller_magnitudes),
    ("g", None, "gram", "grams", 1, 0, 0, 1, 0, 0, all_magnitudes),
    ("A", None, "amp", "amps", 1, 0, 0, 0, 1, 0, all_magnitudes),
    ("K", None, "kelvin", "kelvin", 1, 0, 0, 0, 0, 1, all_magnitudes) ]

derived_si_units = [
    ("Hz", None, "hertz", "hertz", 1, 0, -1, 0, 0, 0, all_magnitudes),
    ("N", None, "newton", "newtons", 1, 1, -2, 1, 0, 0, all_magnitudes),
    ("Pa", None, "pascal", "pascals", 1, -1, -2, 1, 0, 0, all_magnitudes),
    ("J", None, "joule", "joules", 1, 2, -2, 1, 0, 0, all_magnitudes),
    ("W", None, "watt", "watts", 1, 2, -3, 1, 0, 0, all_magnitudes),
    ("C", None, "coulomb", "coulombs", 1, 0, 1, 0, 1, 0, all_magnitudes),
    ("V", None, "volts", "volts", 1, 2, -3, 1, -1, 0, all_magnitudes),
    ("Ohm", "Ω", "ohm", "ohms", 1, 2, -3, 1, -2, 0, all_magnitudes),
    ("F", None, "farad", "farads", 1, -2, 4, -1, 2, 0, all_magnitudes),
    ("S", None, "siemens", "siemens", 1, -2, 3, -1, 2, 0, all_magnitudes),
    ("Wb", None, "weber", "webers", 1, 2, -2, 1, -1, 0, all_magnitudes),
    ("T", None, "tesla", "tesla", 1, 2, -2, 1, -1, 0, all_magnitudes),
    ("H", None, "henry", "henry", 1, 2, -2, 1, -2, 0, all_magnitudes),
    ("C", None, "degree Celsius", "degrees Celsius", 1, 0, 0, 0, 0, 1, [])
]

non_si_units = [
    ("A", None, "angstrom", "angstroms", 1e-10, 1, 0, 0, 0, 0, []),
    ("min", None, "minute", "minutes", 60, 0, 1, 0, 0, 0, []),
    ("hr", None, "hour", "hours", 360, 0, 1, 0, 0, 0, []),
    ("d", None, "day", "days", 360*24, 0, 1, 0, 0, 0, []),
    ("day", None, "day", "days", 360*24, 0, 1, 0, 0, 0, []),
    ("y", None, "year", "years", 360*24*365.2425, 0, 1, 0, 0, 0, []),
    ("yr", None, "year", "years", 360*24*365.2425, 0, 1, 0, 0, 0, []),
    ("deg", None, "degree", "degrees", 180/np.pi, 0, 0, 0, 0, 0, []),
    ("rad", None, "radian", "radians", 1, 0, 0, 0, 0, 0, []),
    ("sr", None, "stradian", "stradians", 1, 0, 0, 0, 0, 0, [])
]

all_units = base_si_units + derived_si_units + non_si_units

encoding = "utf-8"

def write_unit_string(fid, symbol, special_symbol, singular, plural, scale, length, time, mass, current, temperature):
    fid.write(f"'{symbol}', '{special_symbol}', '{singular}', '{plural}', ")
    fid.write(f"{scale}, {length}, {time}, {mass}, {current}, {temperature}\n")


with open("unit_data.txt", mode='w', encoding=encoding) as fid:
    for symbol, special_symbol, singular, plural, scale, length, time, mass, current, temperature, magnitudes in all_units:

        write_unit_string(fid, symbol, special_symbol, singular, plural,
                          scale, length, time, mass, current, temperature)

        for mag_symbol, mag_special_symbol, name, mag_scale in magnitudes:

            combined_symbol = (mag_symbol if mag_special_symbol is None else mag_special_symbol) + \
                              (symbol if special_symbol is None else special_symbol)

            write_unit_string(fid,f"{mag_symbol}{symbol}", combined_symbol, f"{name}{singular}",
                              f"{name}{plural}", scale * mag_scale, length, time, mass, current, temperature)


def format_name(name: str):
    return name.replace(" ", "_")

header = """

Autogenerated file by units_table.py



    ********  DO NOT EDIT BY HAND  ********



"""

with open("units.py", 'w', encoding=encoding) as fid:

    # Write warning header
    fid.write('"""'+header+'"""')

    # Write in class definitions
    fid.write("\n\n"
              "#\n"
              "# Included from units_base.py\n"
              "#\n\n")

    with open("units_base.py", 'r') as base:
        for line in base:
            fid.write(line)

    # Write in unit definitions
    fid.write("\n\n"
              "#\n"
              "# Specific units \n"
              "#\n\n")

    symbol_lookup = {}
    unit_types = defaultdict(list)

    for symbol, special_symbol, singular, plural, scale, length, time, mass, current, temperature, magnitudes in all_units:

        formatted_plural = format_name(plural)

        fid.write(f"{formatted_plural} = Unit({scale}, Dimensions({length}, {time}, {mass}, {current}, {temperature}))\n")

        symbol_lookup[symbol] = formatted_plural
        if special_symbol is not None:
            symbol_lookup[special_symbol] = formatted_plural

        for mag_symbol, mag_special_symbol, name, mag_scale in magnitudes:

            combined_special_symbol = (mag_symbol if mag_special_symbol is None else mag_special_symbol) + \
                              (symbol if special_symbol is None else special_symbol)

            combined_symbol = mag_symbol + symbol

            combined_name = f"{name}{formatted_plural}"

            fid.write(f"{combined_name} = Unit({scale * mag_scale}, Dimensions({length}, {time}, {mass}, {current}, {temperature}))\n")

            symbol_lookup[combined_symbol] = combined_name
            symbol_lookup[combined_special_symbol] = combined_name

    fid.write("symbol_lookup = {\n")
    for k in symbol_lookup:
        fid.write(f'        "{k}": {symbol_lookup[k]},\n')
    fid.write("}\n\n")

