name: Tests

on:
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  unit-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.12']
      fail-fast: false

    steps:

    - name: Obtain SasData source from git
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          **/test.yml
          **/requirements*.txt

    ### Installation of build-dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install -r requirements.txt
        python -m pip install -r sasdata/fair_database/requirements.txt

    ### Build and test sasdata

    - name: Build sasdata
      run: |
        # BUILD SASDATA
        python -m pip install -e .

    ### Build documentation (if enabled)

    - name: Test with Django tests
      run: |
        python sasdata/fair_database/manage.py test sasdata.fair_database
